// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: balance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{0}
}

type UpdateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLimitRequest) Reset() {
	*x = UpdateLimitRequest{}
	mi := &file_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLimitRequest) ProtoMessage() {}

func (x *UpdateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLimitRequest.ProtoReflect.Descriptor instead.
func (*UpdateLimitRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateLimitRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateLimitRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type UpdateBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceRequest) Reset() {
	*x = UpdateBalanceRequest{}
	mi := &file_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceRequest) ProtoMessage() {}

func (x *UpdateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBalanceRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateBalanceRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type OpenReservationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OwnerServiceId int64                  `protobuf:"varint,2,opt,name=owner_service_id,json=ownerServiceId,proto3" json:"owner_service_id,omitempty"`
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpenReservationRequest) Reset() {
	*x = OpenReservationRequest{}
	mi := &file_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenReservationRequest) ProtoMessage() {}

func (x *OpenReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenReservationRequest.ProtoReflect.Descriptor instead.
func (*OpenReservationRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{3}
}

func (x *OpenReservationRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *OpenReservationRequest) GetOwnerServiceId() int64 {
	if x != nil {
		return x.OwnerServiceId
	}
	return 0
}

func (x *OpenReservationRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OpenReservationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *OpenReservationRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ReservationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservationId  int64                  `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	AccountId      int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OwnerServiceId int64                  `protobuf:"varint,3,opt,name=owner_service_id,json=ownerServiceId,proto3" json:"owner_service_id,omitempty"`
	Amount         int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ExpiresAt      int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReservationResponse) Reset() {
	*x = ReservationResponse{}
	mi := &file_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationResponse) ProtoMessage() {}

func (x *ReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationResponse.ProtoReflect.Descriptor instead.
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{4}
}

func (x *ReservationResponse) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

func (x *ReservationResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ReservationResponse) GetOwnerServiceId() int64 {
	if x != nil {
		return x.OwnerServiceId
	}
	return 0
}

func (x *ReservationResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReservationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReservationResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ReservationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservationId  int64                  `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OwnerServiceId int64                  `protobuf:"varint,2,opt,name=owner_service_id,json=ownerServiceId,proto3" json:"owner_service_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReservationRequest) Reset() {
	*x = ReservationRequest{}
	mi := &file_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationRequest) ProtoMessage() {}

func (x *ReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationRequest.ProtoReflect.Descriptor instead.
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{5}
}

func (x *ReservationRequest) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

func (x *ReservationRequest) GetOwnerServiceId() int64 {
	if x != nil {
		return x.OwnerServiceId
	}
	return 0
}

var File_balance_proto protoreflect.FileDescriptor

const file_balance_proto_rawDesc = "" +
	"\n" +
	"\rbalance.proto\x12\abalance\"\a\n" +
	"\x05Empty\"I\n" +
	"\x12UpdateLimitRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\"K\n" +
	"\x14UpdateBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\"\xcb\x01\n" +
	"\x16OpenReservationRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12(\n" +
	"\x10owner_service_id\x18\x02 \x01(\x03R\x0eownerServiceId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\"\xd4\x01\n" +
	"\x13ReservationResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\x03R\rreservationId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12(\n" +
	"\x10owner_service_id\x18\x03 \x01(\x03R\x0eownerServiceId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"e\n" +
	"\x12ReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\x03R\rreservationId\x12(\n" +
	"\x10owner_service_id\x18\x02 \x01(\x03R\x0eownerServiceId2\xe3\x02\n" +
	"\x0eBalanceService\x12:\n" +
	"\vUpdateLimit\x12\x1b.balance.UpdateLimitRequest\x1a\x0e.balance.Empty\x12>\n" +
	"\rUpdateBalance\x12\x1d.balance.UpdateBalanceRequest\x1a\x0e.balance.Empty\x12P\n" +
	"\x0fOpenReservation\x12\x1f.balance.OpenReservationRequest\x1a\x1c.balance.ReservationResponse\x12A\n" +
	"\x12ConfirmReservation\x12\x1b.balance.ReservationRequest\x1a\x0e.balance.Empty\x12@\n" +
	"\x11CancelReservation\x12\x1b.balance.ReservationRequest\x1a\x0e.balance.EmptyB.Z,test_nanimai/backend/internal/api/grpc/pb;pbb\x06proto3"

var (
	file_balance_proto_rawDescOnce sync.Once
	file_balance_proto_rawDescData []byte
)

func file_balance_proto_rawDescGZIP() []byte {
	file_balance_proto_rawDescOnce.Do(func() {
		file_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)))
	})
	return file_balance_proto_rawDescData
}

var file_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_balance_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: balance.Empty
	(*UpdateLimitRequest)(nil),     // 1: balance.UpdateLimitRequest
	(*UpdateBalanceRequest)(nil),   // 2: balance.UpdateBalanceRequest
	(*OpenReservationRequest)(nil), // 3: balance.OpenReservationRequest
	(*ReservationResponse)(nil),    // 4: balance.ReservationResponse
	(*ReservationRequest)(nil),     // 5: balance.ReservationRequest
}
var file_balance_proto_depIdxs = []int32{
	1, // 0: balance.BalanceService.UpdateLimit:input_type -> balance.UpdateLimitRequest
	2, // 1: balance.BalanceService.UpdateBalance:input_type -> balance.UpdateBalanceRequest
	3, // 2: balance.BalanceService.OpenReservation:input_type -> balance.OpenReservationRequest
	5, // 3: balance.BalanceService.ConfirmReservation:input_type -> balance.ReservationRequest
	5, // 4: balance.BalanceService.CancelReservation:input_type -> balance.ReservationRequest
	0, // 5: balance.BalanceService.UpdateLimit:output_type -> balance.Empty
	0, // 6: balance.BalanceService.UpdateBalance:output_type -> balance.Empty
	4, // 7: balance.BalanceService.OpenReservation:output_type -> balance.ReservationResponse
	0, // 8: balance.BalanceService.ConfirmReservation:output_type -> balance.Empty
	0, // 9: balance.BalanceService.CancelReservation:output_type -> balance.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_balance_proto_init() }
func file_balance_proto_init() {
	if File_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balance_proto_goTypes,
		DependencyIndexes: file_balance_proto_depIdxs,
		MessageInfos:      file_balance_proto_msgTypes,
	}.Build()
	File_balance_proto = out.File
	file_balance_proto_goTypes = nil
	file_balance_proto_depIdxs = nil
}
